/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ProtoCharMessage ProtoCharMessage;
typedef struct ProtoDisplayMessage ProtoDisplayMessage;


/* --- enums --- */

typedef enum _ProtoDirection {
  PROTO_DIRECTION__UP = 0,
  PROTO_DIRECTION__DOWN = 1,
  PROTO_DIRECTION__LEFT = 2,
  PROTO_DIRECTION__RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO_DIRECTION)
} ProtoDirection;

/* --- messages --- */

struct  ProtoCharMessage
{
  ProtobufCMessage base;
  int32_t msg_type;
  char *ch;
  int32_t ncock;
  ProtoDirection direction;
  size_t n_cockdir;
  ProtoDirection *cockdir;
  char *password;
};
#define PROTO_CHAR_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_char_message__descriptor) \
, 0, NULL, 0, PROTO_DIRECTION__UP, 0,NULL, NULL }


struct  ProtoDisplayMessage
{
  ProtobufCMessage base;
  int32_t posx;
  int32_t posy;
  char *ch;
  int32_t score;
};
#define PROTO_DISPLAY_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_display_message__descriptor) \
, 0, 0, NULL, 0 }


/* ProtoCharMessage methods */
void   proto_char_message__init
                     (ProtoCharMessage         *message);
size_t proto_char_message__get_packed_size
                     (const ProtoCharMessage   *message);
size_t proto_char_message__pack
                     (const ProtoCharMessage   *message,
                      uint8_t             *out);
size_t proto_char_message__pack_to_buffer
                     (const ProtoCharMessage   *message,
                      ProtobufCBuffer     *buffer);
ProtoCharMessage *
       proto_char_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_char_message__free_unpacked
                     (ProtoCharMessage *message,
                      ProtobufCAllocator *allocator);
/* ProtoDisplayMessage methods */
void   proto_display_message__init
                     (ProtoDisplayMessage         *message);
size_t proto_display_message__get_packed_size
                     (const ProtoDisplayMessage   *message);
size_t proto_display_message__pack
                     (const ProtoDisplayMessage   *message,
                      uint8_t             *out);
size_t proto_display_message__pack_to_buffer
                     (const ProtoDisplayMessage   *message,
                      ProtobufCBuffer     *buffer);
ProtoDisplayMessage *
       proto_display_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_display_message__free_unpacked
                     (ProtoDisplayMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtoCharMessage_Closure)
                 (const ProtoCharMessage *message,
                  void *closure_data);
typedef void (*ProtoDisplayMessage_Closure)
                 (const ProtoDisplayMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    proto_direction__descriptor;
extern const ProtobufCMessageDescriptor proto_char_message__descriptor;
extern const ProtobufCMessageDescriptor proto_display_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
