# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x9b\x01\n\x12proto_char_message\x12\x10\n\x08msg_type\x18\x01 \x02(\x05\x12\n\n\x02\x63h\x18\x02 \x02(\t\x12\r\n\x05ncock\x18\x03 \x02(\x05\x12#\n\tdirection\x18\x04 \x02(\x0e\x32\x10.proto_direction\x12!\n\x07\x63ockdir\x18\x05 \x03(\x0e\x32\x10.proto_direction\x12\x10\n\x08password\x18\x06 \x02(\t\"N\n\x15proto_display_message\x12\x0c\n\x04posx\x18\x01 \x02(\x05\x12\x0c\n\x04posy\x18\x02 \x02(\x05\x12\n\n\x02\x63h\x18\x03 \x02(\t\x12\r\n\x05score\x18\x04 \x02(\x05*8\n\x0fproto_direction\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROTO_DIRECTION']._serialized_start=255
  _globals['_PROTO_DIRECTION']._serialized_end=311
  _globals['_PROTO_CHAR_MESSAGE']._serialized_start=18
  _globals['_PROTO_CHAR_MESSAGE']._serialized_end=173
  _globals['_PROTO_DISPLAY_MESSAGE']._serialized_start=175
  _globals['_PROTO_DISPLAY_MESSAGE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
